// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var Settings, datgui, deckModel, deckView, settings;
    Settings = (function() {

      function Settings() {
        this.width = 65;
        this.order = 'sorted';
        this.rotation = 0;
      }

      return Settings;

    })();
    settings = new Settings();
    deckModel = new PlayingCards.DeckModel(null, {
      front: true
    });
    deckView = new PlayingCards.DeckView({
      el: $('#cards'),
      model: deckModel,
      templates: new PlayingCards.Templates()
    });
    deckView.setCardWidth(settings.width);
    deckView.render();
    datgui = new dat.GUI();
    datgui.add(settings, 'width').min(10).max(500).step(1).onChange(function(value) {
      return deckView.setCardWidth(value);
    });
    datgui.add(settings, 'order', ['sorted', 'random']).onChange(function(value) {
      switch (value) {
        case 'sorted':
          return deckView.sort();
        case 'random':
          return deckView.shuffle();
      }
    });
    return datgui.add(settings, 'rotation').min(0).max(360).step(1).onChange(function(value) {
      return deckView.$el.css({
        '-ms-transform': "rotate(" + value + "deg)",
        '-moz-transform': "rotate(" + value + "deg)",
        '-webkit-transform': "rotate(" + value + "deg)",
        'transform': "rotate(" + value + "deg)"
      });
    });
  });

}).call(this);
